name: Auto Ping Bots

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"    # 00:00
    - cron: "0 5 * * *"    # 05:00
    - cron: "0 10 * * *"   # 10:00
    - cron: "0 15 * * *"   # 15:00
    - cron: "0 20 * * *"   # 20:00
  push:
    branches:
      - main

jobs:
  run-botvip:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install --upgrade python-telegram-bot

      - name: Run botvip.py
        run: python botvip.py

  run-botluuaccfb:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install --upgrade python-telegram-bot

      - name: Run botluuaccfb.py
        run: python botluuaccfb.py

  commit-files:
    runs-on: ubuntu-latest
    needs: [run-botvip, run-botluuaccfb]
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push any new or changed files
        run: |
          git add .
          git commit -m "Auto commit acc files by bot" || echo "No changes to commit"
          git push origin main